added ci workflow

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -49,6 +49,16 @@ jobs:
     - name: check backend syntax
       run: node --check backend/app.js   
 
+       # 8. Check Docker Hub username
+    - name: Check Docker Hub configuration
+      run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "ERROR: DOCKERHUB_USERNAME secret is not configured."
+            exit 1
+          fi
+
+          echo "Docker Hub username is configured."
+          
    #build backend docker image
    # - name: build backend docker image
    #   run: docker build -t mern-task-manager-backend:ci ./backend
@@ -60,7 +70,7 @@ jobs:
     - name: login to docker hub
       uses: docker/login-action@v3
       with:
-        username: ${{ secrets.DOCKER_USERNAME }}
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
    # - name: set up Buildx
